export const CHANGE_TITLE_LOGIN = "CHANGE_TITLE_LOGIN"
export const CHANGE_TITLE_INFOKURS = "CHANGE_TITLE_INFOKURS"
export const CHANGE_TITLE_BERANDA = "CHANGE_TITLE_BERANDA"

export const AUTH_START = 'AUTH_START'
export const AUTH_SUCCESS = 'AUTH_SUCCESS'
export const AUTH_FAIL = 'AUTH_FAIL'