export const CHANGE_TITLE_LOGIN = "CHANGE_TITLE_LOGIN"
export const CHANGE_TITLE_INFOKURS = "CHANGE_TITLE_INFOKURS"
export const CHANGE_TITLE_BERANDA = "CHANGE_TITLE_BERANDA"

export const DATA_TABLE_INFOKURS_START = "DATA_TABLE_INFOKURS_START"
export const DATA_TABLE_INFOKURS_SUCCESS = "DATA_TABLE_INFOKURS_SUCCESS"
export const DATA_TABLE_INFOKURS_FAIL = "DATA_TABLE_INFOKURS_FAIL"